name: llama_cpp
description: A dart binding for llama.cpp library, bringing AI to dart world.
version: 1.2.0
repository: https://github.com/lindeer/llama-cpp

topics:
  - llama
  - nlp
  - llm

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  ffi: ^2.1.3
  logging: ^1.3.0
  native_assets_cli: ^0.11.0
  path: ^1.9.1
  native_toolchain_cmake: ^0.0.1

dev_dependencies:
  ffigen: ^16.1.0
  lints: ^3.0.0
  test: ^1.21.0
